ALTER TABLE public.auto_management_history
  ADD COLUMN IF NOT EXISTS signal_status TEXT DEFAULT 'MONITORING',
  ADD COLUMN IF NOT EXISTS current_stop_loss NUMERIC,
  ADD COLUMN IF NOT EXISTS tp1_hit_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS tp2_hit_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS close_reason TEXT,
  ADD COLUMN IF NOT EXISTS peak_pnl_pct NUMERIC;